spring:
  profiles:
    #包含的配置项
    include:
    - single-datasource
    #      - quartz
    #启用配置项级别
    active: prod
  #色彩日志输出
  output:
    ansi:
      enabled: always

mybatis:
  mapper-locations: classpath*:**/mappers/*.xml
  type-aliases-package: cn.com.megalith.domain.entity
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    use-column-label: true
    cache-enabled: true
    call-setters-on-nulls: true
logging:
  level:
    root: info
    org:
      springframework: info
dowload:
  path: /home/leo/Desktop
server:
  port: 8081